ref:
  gtf: /gpfs/projects/bsc83/Data/gene_annotations/gencode/v47/gencode.v47.primary_assembly.annotation.gtf
  gtf_ver: 47

  cerberus:
      ics: ref/cerberus/ics.tsv
      ends: ref/cerberus/{end_mode}.bed
      ref:
        annot_h5: ref/{analysis}/cerberus/ref/ref.h5
      update:
        gtf: ref/{analysis}/cerberus/update/ref.gtf

meta:
  # sample: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/00_metadata/{analysis}/pantranscriptome_samples_metadata.tsv
  sample: ref/pantranscriptome_samples_metadata.tsv
  library: snakemake/config.tsv


params:
  cerberus:
    tss:
      dist: 25 # extension distance
      slack: 0
      agg_slack: 20
    tes:
      dist: 10 # extension dist
      slack: 0
      agg_slack: 20

lyric:
  gff: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/lyric/240910_lyric_complete/{lab_rep}_updated.gff.gz
  gtf: /gpfs/projects/bsc83/Projects/pantranscriptome/fairlie/lyric_raw_not_symlink/{lab_rep}.gtf

iq:
  gtf: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/isoquant/{lab_rep}.transcript_models.gtf

flair:
  gtf: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/flair/{lab_rep}.isoforms.gtf

espresso:
  gtf: /gpfs/projects/bsc83/Projects/pantranscriptome/novelannotations/espresso/{lab_rep}_espresso.gtf

raw:
  gtf: data/{analysis}/raw/{tech_rep}.gtf

fmt:
  novel_gene_bed: data/{analysis}/fmt/{tech_rep}_novel_gene.bed
  novel_gene_gtf: data/{analysis}/fmt/{tech_rep}_novel_gene.gtf
  novel_gene_merge_gtf: data/fmt/novel_gene_merged.gtf
  novel_gene_merge_gtf_no_genes: data/fmt/novel_gene_merged_no_genes.gtf
  novel_gene_merge_build_loci_gtf: data/fmt/novel_gene_build_loci_merged.gtf
  novel_gene_tid_to_gid: data/fmt/novel_gene_tid_to_gid.tsv

  novel_gene_merge_bed: data/{analysis}/fmt/novel_gene_merged.bed
  novel_gene_rename_gtf: data/{analysis}/fmt/{tech_rep}_novel_gene_rename.gtf
  gtf: data/{analysis}/fmt/{tech_rep}.gtf

ic_gtf:
  cfg: data/ics_only/cfg.txt
  gtf: data/ics_only/merged.gtf
  # ics: data/{analysis}/ics_only/{tech_rep}_ics.tsv

cerberus:
  ics: data/{analysis}/cerb/{tech_rep}_ics.tsv
  ends: data/{analysis}/cerb/{tech_rep}_{end_mode}.bed
  agg:
      ics_cfg: data/cerb/agg/agg_ic_cfg.csv
      ics: data/cerb/agg/agg_ics.tsv
      ends_cfg: data/cerb/agg/agg_{end_mode}_cfg.csv
      ends: data/cerb/agg/agg_{end_mode}.bed
  ref:
      h5: data/cerb/ref/ref.h5
      annot_h5: data/cerb/ref/{tech_rep}.h5
  update:
      gtf: data/cerb/update/{tech_rep}.gtf
  merge:
      cfg: data/cerb/update/cfg.tsv
      gtf: data/cerb/update/merged.gtf
      cfg_h5: data/cerb/update/cfg_h5.tsv
      h5: data/cerb/update/merged.h5

software:
  buildLoci: /gpfs/home/bsc/bsc083001/mele_lab/bin/buildLoci/buildLoci.pl
