ref:
  gtf: /gpfs/projects/bsc83/Data/gene_annotations/gencode/v47/gencode.v47.primary_assembly.annotation.gtf
  gtf_ver: 47

  cerberus:
      ics: ref/cerberus/ics.tsv
      ends: ref/cerberus/{end_mode}.bed
meta:
  sample: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/00_metadata/pantranscriptome_samples_metadata.tsv
  # library: snakemake/iq_masked_genomic_config.tsv
  library: snakemake/config.tsv

params:
  cerberus:
    tss:
      dist: 25 # extension distance
      slack: 0
      agg_slack: 20
    tes:
      dist: 10 # extension dist
      slack: 0
      agg_slack: 20

# isoquant
iq:
  gtf: /gpfs/projects/bsc83/Projects/pantranscriptome/pclavell/04_transcriptome_assembly/02_isoquant/data/unmasked_genomic_guided/{lab_rep}/{lab_rep}.transcript_models.gtf

cerberus:
  ics: data/cerb/{tech_rep}_ics.tsv
  ends: data/cerb/{tech_rep}_{end_mode}.bed
  agg:
      ics_cfg: data/cerb/agg/agg_ic_cfg.csv
      ics: data/cerb/agg/agg_ics.tsv

      ends_cfg: data/cerb/agg/agg_{end_mode}_cfg.csv
      ends: data/cerb/agg/agg_{end_mode}.bed
